spring:
  mvc:
    static-path-pattern: /static/**
    favicon.enabled: false
  custom:
    admin-password: ${ADMIN_PASSWORD}
  thymeleaf.cache: false
  web:
    resources:
      add-mappings: true
      static-locations: classpath:/static/
  application:
    name: shopping-cart
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  devtools:
    livereload.enabled: true
    restart.enabled: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shopping_cart
    username: ${DB_ROOT_USERNAME}
    password: ${DB_ROOT_PASSWORD}

  jpa:
    database: mysql
    open-in-view: true
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        show_sql: true
        format_sql: true

  flyway:
    enabled: false
logging:
  #  file:
  #    name: shopping-cart.log
  level:
    root: INFO
    org.springframework.messaging: INFO
    org.hibernate.orm.jdbc.bind: ERROR
    dev.thural.shopping-cart.service: INFO
    org.springframework.security: DEBUG
    org.hibernate:
      sql: DEBUG
      type.descriptor.sql.BasicBinder: TRACE
    org.springframework.web.servlet.handler.HandlerMappingIntrospector: ERROR
  logback:
    rollingpolicy:
      max-file-size: 2MB
      max-history: 3
server:
  port: 8080
  error.whitelabel.enabled: false

file:
  upload-dir: ./uploads
