version: '3.8'
services:

  shopping-cart-db:
    container_name: shopping-cart
    image: mysql:8.0
    restart: on-failure
    volumes:
      - monolith_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER_USERNAME}
      MYSQL_PASSWORD: ${DB_USER_PASSWORD}
    networks:
      - monolith-network
    ports:
      - ${DB_PORT_NUMBER}:3306

#  shopping-cart:
#    build:
#      context: ../..
#      dockerfile: buildfiles/Dockerfile
#    image: thural/shopping-cart:latest
#    depends_on:
#      - shopping-cart-db
#    env_file:
#      - ./.env
#    networks:
#      - monolith-network
#    ports:
#      - ${SERVER_PORT_NUMBER}:8080
#    volumes:
#      - ./:/app
#      - /target

volumes:
  monolith_data:

networks:
  monolith-network:
    name: monolith-network
    driver: bridge
    external: true